Final Docker file creation

diff --git a/.github/workflows/Create_docker_file.yml b/.github/workflows/Create_docker_file.yml
--- a/.github/workflows/Create_docker_file.yml
+++ b/.github/workflows/Create_docker_file.yml
@@ -17,8 +17,13 @@ jobs:
       - name: Extract Java version from pom.xml
         id: extract_java_version
         run: |
-          JAVA_VERSION=$(mvn help:evaluate -Dexpression=maven.compiler.source -q -DforceStdout)
+          JAVA_VERSION=$(mvn help:evaluate -Dexpression=project.properties.java.version -q -DforceStdout)
+          if [ -z "$JAVA_VERSION" ]; then
+            echo "Version not found!"
+            exit 1
+          fi
           echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
+          echo "Java version: $JAVA_VERSION"
 
       - name: Extract version and app file name from pom.xml
         id: extract_version
@@ -30,6 +35,7 @@ jobs:
           fi
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "JAR_FILE=HouseManagement-$VERSION.jar" >> $GITHUB_ENV
+          echo "Version: $VERSION"
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
